#!/bin/bash
# Generate btrfs test images with real mkfs.btrfs.
#
# Needs Linux: there is no btrfs-progs for macOS, and two of the three images
# have to be mounted to be populated. Run it in the colima VM:
#
#   colima ssh -- bash -lc 'mkdir -p /tmp/btrfs && cd /tmp/btrfs'
#   colima ssh -- tee /tmp/btrfs/gen.sh < tools/gen-btrfs-fixtures.sh
#   colima ssh -- bash /tmp/btrfs/gen.sh /tmp/btrfs/out
#
# A second argument limits which images are built, so adding a fixture does not
# churn the three that are already committed:
#
#   colima ssh -- sudo bash /tmp/btrfs/gen.sh /tmp/btrfs/out subvol
#   colima ssh -- tar -C /tmp/btrfs/out -cf - . | tar -C fixtures/btrfs -xf -
#
# Same rule as every other fixture in this repo: the test data comes from the
# real tool, never from our own writer. A misreading of the on-disk format
# would otherwise appear identically in the generator and the reader, and the
# tests would pass while a real drive failed.
#
# Sizes look alarming (~106 MiB each) but that is btrfs's minimum for a
# non-mixed filesystem, and the images are almost entirely zeros: plain.img
# gzips to 117 KiB, so the cost in git is negligible.
set -euo pipefail

OUT="${1:-/tmp/btrfs-fixtures}"
TARGETS="${2:-plain compress mixed-4k subvol}"
UUID_PLAIN="33333333-4444-5555-6666-777777777777"
UUID_COMPRESS="88888888-9999-aaaa-bbbb-cccccccccccc"
UUID_MIXED="11111111-2222-3333-4444-555555555555"
UUID_SUBVOL="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

want() { case " $TARGETS " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

command -v mkfs.btrfs >/dev/null || { echo "mkfs.btrfs not found: apt-get install btrfs-progs"; exit 1; }
[ "$(uname -s)" = Linux ] || { echo "Linux only — run this in the VM"; exit 1; }

mkdir -p "$OUT"
WORK="$(mktemp -d)"
MNT="$WORK/mnt"
cleanup() {
    umount "$MNT" 2>/dev/null || true
    rm -rf "$WORK"
}
trap cleanup EXIT
mkdir -p "$MNT"

# --- deterministic content -------------------------------------------------
# Everything here is reproducible from the test, so assertions compare against
# regenerated bytes rather than against hashes nobody can re-derive.
ROOT="$WORK/root"
mkdir -p "$ROOT/docs/nested" "$ROOT/many"
python3 - "$ROOT" <<'PY'
import sys, pathlib
root = pathlib.Path(sys.argv[1])
(root / "hello.txt").write_bytes(b"hello btrfs\n")
(root / "docs/readme.md").write_bytes(b"# readme\n\nnested content\n")
(root / "docs/nested/deep.txt").write_bytes(b"three levels down\n")
(root / "café-naïve-日本語.txt").write_bytes("unicode name\n".encode())
# 2 MiB: several extents, and big enough that the file's EXTENT_DATA items do
# not all fit beside its inode item.
(root / "big.bin").write_bytes(bytes((i * 31 + 7) % 256 for i in range(2 * 1024 * 1024)))
# 400 files force the fs tree past a single 16 KiB leaf, so the reader has to
# descend interior nodes rather than getting away with reading one block.
for i in range(400):
    (root / "many" / f"f{i:04d}.txt").write_bytes(f"file number {i}\n".encode())
PY
ln -s hello.txt "$ROOT/link-to-hello"
ln -s nested/deep.txt "$ROOT/docs/link-to-deep"

# --- plain.img: the workhorse ----------------------------------------------
# --rootdir populates without mounting, so no root and no loop device. Default
# geometry: 4 KiB sectors, 16 KiB nodes, and metadata DUP — which means the
# metadata chunk has two stripes for the same logical range and the reader has
# to pick one. That is not an exotic case; it is what mkfs does by default on
# anything it does not think is an SSD.
if want plain; then
echo "Building plain.img..."
IMG="$OUT/plain.img"
rm -f "$IMG"
truncate -s 1G "$IMG"
mkfs.btrfs -q -L BTRFSTEST -U "$UUID_PLAIN" --rootdir "$ROOT" --shrink "$IMG"
echo "  -> plain.img"
fi

# --- compress.img: the three compression algorithms, plus holes -------------
# compress-force, not compress: the heuristic will happily leave a file
# uncompressed and then the fixture proves nothing.
if want compress; then
echo "Building compress.img..."
IMG="$OUT/compress.img"
rm -f "$IMG"
# 160 MiB is just above btrfs's ~109 MiB floor for a non-mixed filesystem.
# --shrink is not available here because the image has to be mounted to be
# populated, and there is no offline shrink.
truncate -s 160M "$IMG"
mkfs.btrfs -q -L BTRFSCOMP -U "$UUID_COMPRESS" "$IMG"

python3 - "$WORK/payload.txt" <<'PY'
import sys, pathlib
# 256 KiB of text that compresses hard but is not one repeated byte — a single
# repeated byte can be encoded in ways that hide extent-splitting bugs.
lines = [f"line {i:06d} the quick brown fox jumps over the lazy dog\n" for i in range(5000)]
pathlib.Path(sys.argv[1]).write_text("".join(lines))
PY

for algo in zlib lzo zstd; do
    mount -o "loop,compress-force=$algo" "$IMG" "$MNT"
    cp "$WORK/payload.txt" "$MNT/$algo.txt"
    sync
    umount "$MNT"
done

mount -o loop "$IMG" "$MNT"
# 100 bytes: below max_inline (2048), so this lands in the inode's leaf as an
# inline extent instead of getting a data block of its own.
printf 'inline extent, stored in the leaf itself, no data block allocated at all\n' > "$MNT/tiny.txt"
# A hole. NO_HOLES is on by default now, so there is no EXTENT_DATA item
# covering the gap at all — the reader must infer zeros from a *missing* item,
# which is the failure mode that returns garbage instead of erroring.
truncate -s 1048576 "$MNT/sparse.bin"
printf 'end' | dd of="$MNT/sparse.bin" bs=1 seek=1048573 conv=notrunc status=none
sync
umount "$MNT"
echo "  -> compress.img"
fi

# --- mixed-4k.img: nodesize == sectorsize ----------------------------------
# Mixed block groups put data and metadata in one chunk (type DATA|METADATA)
# and force nodesize down to the sector size. It catches anything that assumed
# 16 KiB nodes or that a chunk is only ever one of the two.
if want mixed-4k; then
echo "Building mixed-4k.img..."
IMG="$OUT/mixed-4k.img"
rm -f "$IMG"
truncate -s 64M "$IMG"
mkfs.btrfs -q -M -L BTRFSMIX -U "$UUID_MIXED" --nodesize 4096 "$IMG"
mount -o loop "$IMG" "$MNT"
mkdir -p "$MNT/docs"
printf 'hello mixed\n' > "$MNT/hello.txt"
printf 'nested content\n' > "$MNT/docs/readme.md"
# Both files above are small enough to be stored inline, inside a tree node,
# which means this image had no out-of-line data at all — and so could not
# exercise data checksums, whose whole subject is data outside the trees.
# 1 MiB is past any inlining threshold. It matters here specifically because
# nodesize == sectorsize in mixed mode, which is where an off-by-one in
# per-sector checksum indexing would be invisible on the other images.
python3 -c "import sys; sys.stdout.buffer.write(bytes((i*17+3)%256 for i in range(1024*1024)))" > "$MNT/data.bin"
sync
umount "$MNT"
echo "  -> mixed-4k.img"
fi

# --- subvol.img: more than one fs tree --------------------------------------
# The fixture the developer's own drive needs. A Fedora install keeps / and
# /home in separate subvolumes, and a subvolume is a *separate fs tree* — a
# directory entry pointing at one carries a tree id where every other entry
# carries an inode number. Read it as an inode number and you land on an
# unrelated file in the wrong tree, with checksums that all verify.
#
# The layout is deliberately awkward:
#
#   /toplevel.txt              plain file, proves the top level is still normal
#   /plaindir/note.txt         plain directory, must NOT be treated as a crossing
#   /root/etc/hostname         subvolume off the top level (the Fedora shape)
#   /home/user/docs/deep.txt   subvolume, content several levels down
#   /home/user/snap/inside.txt subvolume nested *inside another subvolume*
#   /snapshots/home-snap/...   read-only snapshot, parent dir is not the root
#
# The last two are the ones that break a naive implementation: a nested
# subvolume means a single path crosses two tree boundaries, and a snapshot
# under `snapshots/` has a parent dirid that is not 256, so reconstructing its
# path needs the INODE_REF chain rather than "/" + name.
if want subvol; then
echo "Building subvol.img..."
IMG="$OUT/subvol.img"
rm -f "$IMG"
truncate -s 160M "$IMG"
mkfs.btrfs -q -L BTRFSSUBV -U "$UUID_SUBVOL" "$IMG"
mount -o loop "$IMG" "$MNT"

printf 'top level file\n' > "$MNT/toplevel.txt"
mkdir -p "$MNT/plaindir"
printf 'just a directory\n' > "$MNT/plaindir/note.txt"

btrfs subvolume create "$MNT/root"
mkdir -p "$MNT/root/etc"
printf 'fixture.localdomain\n' > "$MNT/root/etc/hostname"

btrfs subvolume create "$MNT/home"
mkdir -p "$MNT/home/user/docs"
printf 'four levels down, in another tree\n' > "$MNT/home/user/docs/deep.txt"
btrfs subvolume create "$MNT/home/user/snap"
printf 'nested subvolume\n' > "$MNT/home/user/snap/inside.txt"

mkdir -p "$MNT/snapshots"
btrfs subvolume snapshot -r "$MNT/home" "$MNT/snapshots/home-snap"

sync
# The default subvolume decides what a plain `mount` shows. Setting it proves
# the reader reports it, and — more useful — that browsing still starts from
# the real top level so nothing becomes unreachable.
btrfs subvolume set-default "$MNT/root"
btrfs subvolume list "$MNT" > "$WORK/subvol-list.txt"
btrfs subvolume get-default "$MNT" >> "$WORK/subvol-list.txt"
sync
umount "$MNT"
echo "  -> subvol.img"
fi

# --- ground truth -----------------------------------------------------------
{
    echo "btrfs fixtures — generated by tools/gen-btrfs-fixtures.sh"
    echo "btrfs-progs: $(mkfs.btrfs --version | head -1)"
    echo
    if [ -f "$WORK/subvol-list.txt" ]; then
        echo "=== subvol.img: subvolumes ==="
        cat "$WORK/subvol-list.txt"
        echo
    fi
    for img in $TARGETS; do
        echo "=== $img.img ==="
        btrfs inspect-internal dump-super "$OUT/$img.img" |
            grep -E '^(magic|fsid|label|generation|root|chunk_root|log_root|total_bytes|sectorsize|nodesize|sys_array_size|root_level|chunk_root_level|num_devices|incompat_flags|csum_type)\b'
        echo
        echo "--- chunk tree ---"
        btrfs inspect-internal dump-tree -t chunk "$OUT/$img.img" | grep -E 'CHUNK_ITEM|length|stripe [0-9]'
        echo
    done
    # A partial run must not clobber the ground truth for images it did not
    # build; the section it does produce gets appended to the tracked file.
} > "$OUT/BTRFS-EXPECTED.partial.txt" 2>&1
case "$TARGETS" in
    "plain compress mixed-4k subvol") mv "$OUT/BTRFS-EXPECTED.partial.txt" "$OUT/BTRFS-EXPECTED.txt" ;;
esac

echo "Done:"
ls -la "$OUT"
